services:
  bot:
    build: .
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  worker:
    build:
      context: .
      dockerfile: worker_Dockerfile
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always


  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000

    restart: always

  redis:
    image: "redis:alpine"

    restart: always

  db:
    image: "postgres:15.3"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tales_db

    restart: always
