"""Initial migration

Revision ID: 0a692901fdc9
Revises: 
Create Date: 2024-05-06 19:19:23.094878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a692901fdc9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('users', sa.Column('chapters_available', sa.Integer(), server_default='1', nullable=False))
    op.drop_column('users', 'chain_phase')
    op.drop_column('users', 'chain_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chain_type', postgresql.ENUM('START', 'SUBSCRIBE', 'SECOND_CHAPTER', name='chaintype'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('chain_phase', postgresql.ENUM('FIRST', 'SECOND', 'THIRD', name='chainstage'), autoincrement=False, nullable=True))
    op.drop_column('users', 'chapters_available')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
