"""empty message

Revision ID: 1593c836d1fc
Revises: 491168926a18
Create Date: 2024-05-08 17:22:38.939883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1593c836d1fc'
down_revision: Union[str, None] = '491168926a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('childs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='genderenum'), nullable=False),
    sa.Column('age', sa.Enum('three', 'four', 'five', 'six', 'seven', 'eight', name='ageenum'), nullable=False),
    sa.Column('parent_tg_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['parent_tg_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    subscriptionenum = sa.Enum('trial_plan', 'min_plan', 'standard_plan', 'max_plan', name='subscriptionenum')
    subscriptionenum.create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('subscription_plan', sa.Enum('trial_plan', 'min_plan', 'standard_plan', 'max_plan', name='subscriptionenum'), server_default='trial_plan', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_plan')
    op.drop_table('childs')
    # ### end Alembic commands ###
