"""child name and activities

Revision ID: 60bd9047edcf
Revises: cc22636ac3ea
Create Date: 2024-08-19 20:52:46.210405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60bd9047edcf'
down_revision: Union[str, None] = 'cc22636ac3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('childs', sa.Column('name', sa.String(), nullable=True))
    op.add_column('childs', sa.Column('activities', sa.String(), nullable=True))
    op.drop_constraint('childs_parent_tg_id_fkey', 'childs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('childs_parent_tg_id_fkey', 'childs', 'users', ['parent_tg_id'], ['tg_id'])
    op.drop_column('childs', 'activities')
    op.drop_column('childs', 'name')
    # ### end Alembic commands ###
