"""empty message

Revision ID: 9b6b3cca2f49
Revises: ded6453e5dc8
Create Date: 2024-05-08 19:39:57.479837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b6b3cca2f49'
down_revision: Union[str, None] = 'ded6453e5dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    segment_enum = sa.Enum('start', 'channel_sub', 'second_episode', 'plan', 'payed', name='segmentenum')
    segment_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('segment', sa.Enum('start', 'channel_sub', 'second_episode', 'plan', 'payed', name='segmentenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'segment')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
